### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kanerty** [RimoChan/sese-engine#44]
每一条打印消息前都有这个错误，要如何解决?
(已尝试重新部署，但无法解决)

另外所有数据均为零，会不会有些奇怪...

以下是一部分内容

```
IndexError: list index out of range
收到请求数: 0it [00:00, ?it/s]
丢弃行数: 0it [00:00, ?it/s]
内存行数:   0%|                          | 0/10000000 [00:00<?, ?it/s]
小清洗次数: 0it [00:00, ?it/s]
大清洗索引数: 0it [00:00, ?it/s]
内存键数: 0it [00:00, ?it/s]
内存键数: 0it [00:00, ?it/s]    Traceback (most recent call last):
  File "收获服务器.py", line 172, in <module>
    _抽样检查(word)0, ?it/s]
  File "收获服务器.py", line 164, in _抽样检查
    小 = zt[:单键最多url][-1]]
IndexError: list index out of range
收到请求数: 0it [00:00, ?it/s]
丢弃行数: 0it [00:00, ?it/s]
内存行数:   0%|                          | 0/10000000 [00:00<?, ?it/s]
小清洗次数: 0it [00:00, ?it/s]
大清洗索引数: 0it [00:00, ?it/s]
内存键数: 0it [00:00, ?it/s]
内存键数: 0it [00:00, ?it/s]    Traceback (most recent call last):
  File "收获服务器.py", line 172, in <module>
    _抽样检查(word)0, ?it/s]
  File "收获服务器.py", line 164, in _抽样检查
    小 = zt[:单键最多url][-1]]
```

**Comment by RimoChan** [comment]
哎呀，写出bug了，你先把`收获服务器.py`的171~172行注掉吧，就是for和抽样检查的那两行。

**Comment by kanerty** [comment]
好耶!loli开始工作了!

**Comment by RimoChan** [comment]
好！

**Comment by RimoChan** [comment]
https://github.com/RimoChan/sese-engine/commit/f610cc6a456d2cb509f6975ffff116a5b1d8d31a
修好啦！
